# Generated by Django 5.2.5 on 2025-08-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_varients_productvariation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='ProductVariants',
        ),
    ]
