# Generated by Django 5.2.5 on 2025-08-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_productvariation_productvariants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariants',
        ),
        migrations.DeleteModel(
            name='Varients',
        ),
    ]
