# Generated by Django 5.2.5 on 2025-08-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_productvariants_delete_varients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variantions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_categories', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=250)),
                ('variation_value', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
