# Generated by Django 5.2.5 on 2025-08-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variantions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='store.product'),
        ),
    ]
