# Generated by Django 5.2.5 on 2025-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
        ('store', '0006_alter_variantions_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variantions'),
        ),
    ]
